### ISSUE TITLE
VR video on mobile device

### ISSUE THREAD

**Issue by delsner** [videogular/videogular2-showroom#1]
Great library and great showroom!
Thanks.

Unfortunately, I can't get any of the VR examples running on my iPhone (neither Safari nor Chrome). I tried the showroom example, the ng-connect one (https://github.com/videogular/angular-connect-demo) and the one from the website (http://videogular.com/alpha/#/video-vr). It would be great if you could provide some help.

**Comment by Elecash** [comment]
Hi @delsner thank you for your comments :)

About the VR demo, we're relying on A-Frame and I think that right now the mobile support on A-Frame is still under development for 360 videospheres.

Try the online demo here on your mobile, if it doesn't work, it will not work on videogular2 too:
https://aframe.io/examples/showcase/videosphere/
