### ISSUE TITLE
Mixed content problem at the online demo

### ISSUE THREAD

**Issue by dsge** [videogular/videogular2-showroom#2]
Url: https://videogular.github.io/videogular2-showroom/#/

None of the examples actually play the video on Chrome.

The console shows:

> Mixed Content: The page at 'https://videogular.github.io/videogular2-showroom/#/' was loaded over HTTPS, but requested an insecure video 'http://static.videogular.com/assets/videos/videogular.mp4'. This content should also be served over HTTPS.

**Comment by Elecash** [comment]
@dsge that's just a warning but thanks for noticing.

I've rebooted the server and now it's working fine 😄
