### ISSUE TITLE
IDRMLicenseServer Issue

### ISSUE THREAD

**Issue by yomiteffect** [videogular/videogular2-showroom#5]
I get the error below when I used the streaming-player/streaming-player.component.ts file in my app

[ts] Module '"C:/Users/koyo/Documents/same/node_modules/videogular2/streaming"' has no exported member 'IDRMLicenseServer". 
I have imported all the modules in my app.module.ts
Please kindly help to solve this.
My package.json is detailed below
 
1.  "dependencies": {
2.             "@agm/core": "^1.0.0-beta.1",
3.             "@angular-devkit/schematics": "0.0.34",
4.             "@angular/cli": "^1.4.2",
5.         "@angular/common": "^4.4.3",
6.         "@angular/compiler": "4.4.3",
7.         "@angular/compiler-cli": "4.4.3",
8.         "@angular/core": "^4.4.3",
9.         "@angular/forms": "4.4.3",
10.         "@angular/http": "4.4.3",
11.         "@angular/platform-browser": "4.4.3",
12.         "@angular/platform-browser-dynamic": "4.4.3",
13.         "@firebase/app": "^0.1.6",
14.         "@firebase/auth": "^0.3.2",
15.         "@firebase/database": "^0.1.7",
16.         "@firebase/messaging": "^0.1.7",
17.         "@firebase/storage": "^0.1.6",
18.         "@ionic-native/calendar": "^4.3.1",
19.         "@ionic-native/core": "4.3.0",
20.         "@ionic-native/in-app-browser": "^4.3.1",
21.         "@ionic-native/social-sharing": "^4.3.1",
22.         "@ionic-native/splash-screen": "4.3.0",
23.         "@ionic-native/status-bar": "4.3.0",
24.         "@ionic-native/three-dee-touch": "^4.3.1",
25.         "@ionic/storage": "2.0.1",
26.         "angular2-google-maps": "^0.17.0",
27.         "cordova-android": "6.2.3",
28.         "cordova-ios": "^4.5.2",
29.         "cordova-plugin-calendar": "^4.6.0",
30.         "cordova-plugin-compat": "^1.2.0",
31.         "cordova-plugin-device": "^1.1.4",
32.         "cordova-plugin-inappbrowser": "^1.7.1",
33.         "cordova-plugin-splashscreen": "^4.0.3",
34.         "cordova-plugin-statusbar": "^2.2.2",
35.         "cordova-plugin-whitelist": "^1.3.1",
36.         "cordova-plugin-x-socialsharing": "^5.2.0",
37.         "es6-promise-plugin": "^4.1.0",
38.         "firebase": "^4.5.0",
39.         "hls.js": "^0.8.9",
40.         "ionic-angular": "^3.9.2",
41.         "ionic-plugin-keyboard": "^2.2.1",
42.         "ionicons": "3.0.0",
43.         "minimatch": "^3.0.2",
44.         "object-keys": "^1.0.11",
45.         "onesignal-cordova-plugin": "^2.2.2",
46.         "rxjs": "^5.5.6",
47.         "sw-toolbox": "3.6.0",
48.         "videogular2": "^5.6.2",
49.         "zone.js": "0.8.18"
50.     },
51.     "devDependencies": {
52.         "@ionic/app-scripts": "3.0.0",
53.         "typescript": "2.3.4"
54.     },

**Comment by Elecash** [comment]
Please post your questions on the videogular2 repo: https://github.com/videogular/videogular2/issues
